Create pull_request_template.md
new-airbnb/soy-sauce pull request #18
Opened 2019-02-20 19:29 UTC by xingweitian

This is our pull_request_template v0.0.1! Cheers!

If you have any questions with this template, please feel free to contact me!

This PR solves half of #19.

2019-02-21 17:21 UTC, zhangjiangqige reviewed
I suggest we make the questions in this template more answerable. For example

What issue(s) does this PR aim to solve?

(blank place for answers)

What is the purpose of the changes made?

(blank)

What tests are done?

(blank)

Rules/notices should be placed together, perhaps at the top, and the remaining be Q&A's.

2019-02-21 19:47 UTC, xingweitian commented
Sounds good, you are right. I will improve it.

2019-02-22 18:14 UTC, zhangjiangqige requested changes

2019-02-22 18:14 UTC, zhangjiangqige commented on .github/pull_request_template.md
> +(blank place for answers)
don't need to add these here... just leave a blank line

2019-02-22 18:24 UTC, zhangjiangqige approved these changes

2019-02-22 18:25 UTC, merged